#!/usr/bin/bash

if [ $# -eq 0 ]
then
    echo ""
    echo "ERROR: No arguments supplied"
    echo ""
    echo "USAGE:"
    echo "      $0 <zip file to clean>"
    echo ""
    echo "This script cleans ZIP files."
    echo "It removes 'junk' files from a ZIP file (like \*.class files, VS files, etc)"
    echo ""
    echo ""    
    exit 1
fi

FOLDER="$1"

find "$FOLDER" -type f -iname '*.zip' | while read FILE; do
    #unzip -lqq "$FILE" '*_xx.xml' >/dev/null && echo mv -v "$FILE" "$ANOTHER"/

    echo "****************************"
    echo "Cleaning $FILE:"
    zip -d "$FILE" "*/_vti_cnf/*" "*/bin/*" "*/obj/*" "*/\.vs/*" "*/packages/*" "*/\.idea/*" "*/app.config" "*/App.config" "*/Properties/*" "__MACOSX*" "*.DS_Store" "*.sln" "*.suo" "*.csproj" "*.csproj.user" "*.userprefs" "app.config" "*.class" "*/BUILD_VARS.bash" "*/PROJECT_CUSTOMIZER.bash"

    echo ""
done
