(deftheme obsidian-MikePanitz
  "Created 2019-04-23.")

(custom-theme-set-faces
 'obsidian-MikePanitz
 '(font-lock-builtin-face ((t (:foreground "#808080"))))
 '(region ((t (:background "#804000" :foreground "#e0e2e4"))))
 '(highlight ((t (:background "#3c414c"))))
 '(fringe ((t (:background "#232323" :foreground "#cfbfad"))))
 '(cursor ((t (:background "#626262"))))
 '(isearch ((t (:bold t :foreground "#616161" :background "#e2e2e5"))))
 '(mode-line ((t (:foreground "#b2b2b2" :background "#293134" :box nil))))
 '(mode-line-inactive ((t (:foreground "#949494" :background "#293134" :box nil))))
 '(mode-line-buffer-id ((t (:foreground "#898989" :background "#293134"))))
 '(minibuffer-prompt ((t (:bold t :foreground "#708090"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#f0ad6d" :slant italic))))
 '(font-lock-comment-face ((t (:foreground "#f0ad6d" :slant italic))))
 '(font-lock-negation-char-face ((t (:foreground "#e8e2b7"))))
 '(font-lock-constant-face ((t (:foreground "#A082bd"))))
 '(font-lock-doc-face ((t (:foreground "#7d8c93"))))
 '(font-lock-function-name-face ((t (:foreground "#e0e2e4"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "#93c763"))))
 '(font-lock-preprocessor-face ((t (:foreground "#a082bd"))))
 '(font-lock-string-face ((t (:foreground "#ec7600"))))
 '(font-lock-type-face ((t (:foreground "#93c763"))))
 '(font-lock-variable-name-face ((t (:foreground "#678cb1"))))
 '(font-lock-warning-face ((t (:foreground "#ffffff" :background "#ff6523"))))
 '(link ((t (:foreground "#678cb1"))))
 '(org-hide ((t (:foreground "#708090"))))
 '(org-level-1 ((t (:bold t :foreground "#808080" :height 1.1))))
 '(org-level-2 ((t (:bold nil :foreground "#7e8aa2" :height 1.1))))
 '(org-level-3 ((t (:bold t :foreground "#df9f2d" :height 1.1))))
 '(org-level-4 ((t (:bold nil :foreground "#af4f4b" :height 1.0))))
 '(org-date ((t (:underline t :foreground "#f0ad6d") :height 1.1)))
 '(org-footnote ((t (:underline t :foreground "#ad600b"))))
 '(org-link ((t (:underline t :foreground "#e0e2e4"))))
 '(org-special-keyword ((t (:foreground "#e0e2e4"))))
 '(org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
 '(org-block ((t (:foreground "#7d8c93"))))
 '(org-quote ((t (:inherit org-block :slant italic))))
 '(org-verse ((t (:inherit org-block :slant italic))))
 '(org-todo ((t (:bold t :foreground "#e0e2e4"))))
 '(org-done ((t (:bold t :foreground "#708090"))))
 '(org-warning ((t (:underline t :foreground "#ff0000"))))
 '(org-agenda-structure ((t (:weight bold :foreground "#df9f2d"))))
 '(org-agenda-date ((t (:foreground "#e0e2e4" :height 1.2))))
 '(org-agenda-date-weekend ((t (:weight normal :foreground "#808bed"))))
 '(org-agenda-date-today ((t (:weight bold :foreground "#e0e2e4" :height 1.4))))
 '(org-scheduled ((t (:foreground "#eeeeec"))))
 '(org-sexp-date ((t (:foreground "#808080"))))
 '(default ((t (:background "#293134" :foreground "#e0e2e4")))))

(provide-theme 'obsidian-MikePanitz)
